name: Print Date

on:
  push:
    branches:
      - master

jobs:
  print_date:
    runs-on: ubuntu-20.04
    steps:
      - name: Run date
        run: |
           date
          

  print_directory:
    runs-on: ubuntu-20.04
    steps:
      - name: Print directory
        run: |
           ls -l
