name: Print Date

on:
  push:
    branches:
      - master

jobs:
  print_date:
    runs-on: ubuntu-20.04
    steps:
      - name: Run date
        run: |
          echo date
          

  print_directory:
    runs-on: ubuntu-20.04
    steps:
      - name: Print directory
        run: |
          echo ls -a
