name: e2e tests

on:
  push:
    branches:
      - master
jobs:
  test_e2e:
    runs-on: ubuntu-20.04
    steps:
      - uses: cypress-io/github-action@v2.9.7
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:8080
