name: Testing Conditionals

on:
  push:
    branches:
      - master

jobs:
   Test:    
    runs-on: ubuntu-20.04
    steps:
      - name: Say testing
        if: ${{ (! contains(github.event.head_commit.message, '#skips'))}} || ${{(github.event_name == 'push')  }} 
        run: |
          echo "Test"

 
