on:
  push:
    branches:
      master
      
       if: ${{ (! contains(github.event.head_commit.message, '#skips'))}} || ${{(github.event_name == 'push')  }} 
        runs-on: ubuntu-20.04
        echo " Test"
